version: "3.7"
services:
  apache:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: edoc
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
